POST localhost:8080/category/
Content-Type: application/json

{
  "nameUz": "Jahon Bozorlari",
  "nameEn": "World markets",
  "visible": true
}

###

GET localhost:8080/api/categories/language?language=uz