### Create new Profile by admin
POST localhost:8080/profile/
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDQ2MzAxMTEsImlkIjoxLCJlbWFpbCI6ImFiZHVsbGEuZXJtYXRvdjA0MDdAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIrOTk4OTQzMzUxMzI1Iiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA0NzE2NTExLCJpc3MiOiJOZXdzQmxvZyJ9.N_nMbhopWoF9iNyzJQ4x2YpMQztavYRrzYAqefUw7Ss
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDQ2MzAyOTAsImlkIjozLCJlbWFpbCI6ImFiZHVsbGEuZXJtYXRvdjA0QGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiKzk5ODk0NjY1MTMxMyIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzA0NzE2NjkwLCJpc3MiOiJOZXdzQmxvZyJ9.r18DTSMfsAUKDjtZ1N4h-3-plPZfn8Tu0w-KjL9BaWw

{
  "name": "Javlon12",
  "surname": "Ergashev12",
  "email": "jav12.erg@gmail.com",
  "phoneNumber": "+998913334761",
  "password": "QurtQobil3333",
  "role": "PUBLISHER"
}

### Get profile list
GET localhost:8080/profile/?page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODE0NzYxNTEsImlkIjoxMywiZW1haWwiOiJhYmR1bGxhLmVybWF0b3YwNDA3QGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiKzk5ODk0MzM1MTMyNSIsInJvbGUiOiJBRE1JTiIsImV4cCI6MTY4MTU2MjU1MSwiaXNzIjoiTmV3c0Jsb2cifQ.8MEXB6v3-41vdTRGjHCzR7XMpK7QoAoGDEtDwP5dEDk


### Sign up
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "Jambul",
  "surname": "Jambulov",
  "email": "lla.abdu46@gmail.com",
  "phoneNumber": "+998946651344",
  "password": "JambulJambulov2002"
}



### Log in
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "abdulla.ermatov0407@gmail.com",
  "phoneNumber": "+998943351325",
  "password": "admin123"
}


### Init admin
GET localhost:8080/init/admin